### ISSUE TITLE
I got an apache error when sending http request in the virtual box

### ISSUE THREAD

**Issue by angeloh** [ericwhyne/http-ricochet#1]
$ curl http://localhost/ricochet/ricochet?url=http://news.ycombinator.com

configuration error:  couldn't perform authentication. AuthType not set!: /ricochet/ricochet

**Comment by ericwhyne** [comment]
If you deployed it using the included vagrant scripts, it's exposed via port 8080. Try something like this:
curl http://127.0.0.1:8080/ricochet/ricochet?url=http://news.ycombinator.com&ct=text/plain

**Comment by ericwhyne** [comment]
I'll leave this issue open until you let me know if that worked.

**Comment by angeloh** [comment]
Here is what I did to fix it.

$ sudo vim /etc/apache2/sites-enabled/ricochet-apache.conf

```
<Directory /var/www/>
# Require all granted
</Directory>
```

$ sudo vim /etc/apache2/sites-available/default
change to 8080

$ ln -s /etc/apache2/sites-available/default /etc/apache2/sites-enabled/default
