### ISSUE TITLE
Can Ricochet auto follow meta tag http-equiv refresh?

### ISSUE THREAD

**Issue by angeloh** [ericwhyne/http-ricochet#2]
One example is www.amerisourcebergendrug.com.

**Comment by ericwhyne** [comment]
You'd have to parse it client side and kick off another fetch with the new redirected url. In that case the tag looks like <meta http-equiv="REFRESH" content="0; url=http://www.amerisourcebergendrug.com/abcdrug/">  

Building on the example from the http-ricochet documentation, you could do something like this to detect and extract the url:

for meta_tag in soup.find_all('meta'):
  page_links.append(meta_tag.get('url'))

Then continue to use the page_links array to fetch new content or write it to a kafka topic or something to be put into a queue for fetching.
